#!/usr/bin/env python3
"""Generate secrets and write them to .env.

Usage:
    python3 scripts/gen_keys.py

If .env already exists, the script exits without overwriting.
Requires no extra packages — uses Python standard library only.
"""
import base64
import hashlib
import hmac
import json
import os
import secrets
import time


def _b64url(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode()


def make_jwt(payload: dict, secret: str) -> str:
    header = _b64url(json.dumps({"alg": "HS256", "typ": "JWT"}, separators=(",", ":")).encode())
    body = _b64url(json.dumps(payload, separators=(",", ":")).encode())
    signing_input = f"{header}.{body}"
    sig = hmac.new(secret.encode(), signing_input.encode(), hashlib.sha256).digest()
    return f"{signing_input}.{_b64url(sig)}"


ENV_FILE = os.path.join(os.path.dirname(__file__), "..", ".env")


def main():
    if os.path.exists(ENV_FILE):
        print(f".env already exists — delete it first if you want to regenerate.")
        raise SystemExit(1)

    now = int(time.time())
    exp = now + 10 * 365 * 24 * 3600  # 10 years

    jwt_secret = secrets.token_urlsafe(40)

    anon_key = make_jwt(
        {"role": "anon", "iss": "supabase", "iat": now, "exp": exp},
        jwt_secret,
    )
    service_key = make_jwt(
        {"role": "service_role", "iss": "supabase", "iat": now, "exp": exp},
        jwt_secret,
    )

    content = f"""\
# Generated by scripts/gen_keys.py — do not commit this file.

POSTGRES_PASSWORD={secrets.token_urlsafe(24)}
JWT_SECRET={jwt_secret}
ANON_KEY={anon_key}
SERVICE_ROLE_KEY={service_key}
ADMIN_API_KEY={secrets.token_urlsafe(24)}
CORS_ORIGINS=http://localhost
"""

    with open(ENV_FILE, "w") as f:
        f.write(content)

    print(f".env written to {os.path.abspath(ENV_FILE)}")


if __name__ == "__main__":
    main()
